# Data Preperation

In [1]:
import os
import numpy as np

dir = "cifar-10-batches-py"

# testing
# os.path.exists(dir)

def unpickle(file):
    import pickle
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')
    return dict

# Import Train Data
train_data = []
train_labels = []

# for each batch file
for i in range(1, 6):
    data_file = unpickle(dir + f"\\data_batch_{i}")
    train_data.extend(data_file[b"data"])
    train_labels.extend(data_file[b"labels"])

# Import Test Data
test_data = []
test_labels = []

# Test data file
test_data_file = unpickle(dir + "\\test_batch")
test_data = test_data_file[b"data"]

test_labels = test_data_file[b"labels"]

# Convert all to numpy arrays
train_data = np.array(train_data)
train_labels = np.array(train_labels)

test_data = np.array(test_data)
test_labels = np.array(test_labels)

# testing
print(train_data.shape) # shape: 10000, 3072
print(train_labels.shape)
print(test_data.shape)
print(test_labels.shape)
# print(train_labels[0]) # labels are in range 0-9: airplanes, cars, birds, cats, deer, dogs, frogs, horses, ships, and trucks.
# print(train_data[0]) # shape: 3072, 1024 for each RGB color channel

(50000, 3072)
(50000,)
(10000, 3072)
(10000,)


In [2]:
# Get all training data and put it in vertical stack data structure
all_train_data = np.vstack(train_data)
# Normalize all values and data
normalized_train_data = all_train_data / 255.0

# testing
print(normalized_train_data.shape)
print(normalized_train_data)

all_test_data = np.vstack(test_data)

normalized_test_data = all_test_data / 255.0

# testing
# print(test_data)
# print(normalized_test_data)

(50000, 3072)
[[0.23137255 0.16862745 0.19607843 ... 0.54901961 0.32941176 0.28235294]
 [0.60392157 0.49411765 0.41176471 ... 0.54509804 0.55686275 0.56470588]
 [1.         0.99215686 0.99215686 ... 0.3254902  0.3254902  0.32941176]
 ...
 [0.1372549  0.15686275 0.16470588 ... 0.30196078 0.25882353 0.19607843]
 [0.74117647 0.72941176 0.7254902  ... 0.6627451  0.67058824 0.67058824]
 [0.89803922 0.9254902  0.91764706 ... 0.67843137 0.63529412 0.63137255]]


# K Nearest Neighbor

In [3]:
from sklearn.neighbors import KNeighborsClassifier

# knn_results = {}

# for k in range(1, 9):
#   knn = KNeighborsClassifier(k)
#   knn.fit(normalized_train_data, train_labels)
#   pred = knn.predict(normalized_test_data)
#   knn_results[k] = pred

In [4]:
from sklearn.metrics import accuracy_score

# for k, pred in knn_results.items():
#   print(f"k = {k} accuracy: {accuracy_score(test_labels, pred)}")

# Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=1, max_depth=15)

dt.fit(normalized_train_data, train_labels)

pred = dt.predict(normalized_test_data)

# Accuracy with max depth = 15
print(accuracy_score(test_labels, pred))

0.2851


In [7]:
dt = DecisionTreeClassifier(random_state=1, max_depth=25)

dt.fit(normalized_train_data, train_labels)

pred = dt.predict(normalized_test_data)

# Accuracy with max depth = 25
print(accuracy_score(test_labels, pred))

0.2714


# Random Forest

In [9]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100)
rf.fit(normalized_train_data, train_labels)
pred = rf.predict(normalized_test_data)

# Accuracy with max depth = 25
print(accuracy_score(test_labels, pred))

0.4742


In [10]:
rf = RandomForestClassifier(n_estimators=150)
rf.fit(normalized_train_data, train_labels)
pred = rf.predict(normalized_test_data)

# Accuracy with max depth = 25
print(accuracy_score(test_labels, pred))

0.4795


# SVM (i.e., SVC for classification)

# MLP